Fb ajax
FadiBaker92/photogram-ajax pull request #1
Opened 2024-07-11 14:39 UTC by FadiBaker92

2024-07-12 22:17 UTC, ahuynh3a requested changes
Hey fadi! You code looks great! One thing, in your follow_request/destroy.js.erb, you are missing a semicolon after your first line of code so I am unable to destroy the follow, could you add that semicolon? I can approve after!

2024-07-12 22:17 UTC, ahuynh3a commented on app/controllers/comments_controller.rb
> +
nitpik: Please be mindful of any empty whitespaces you might not need, and remove them.

2024-07-12 22:17 UTC, ahuynh3a commented on app/views/follow_requests/_follow_unfollow.html.erb
> +<div class="<%=dom_id(recipient)%>_<%=dom_id(sender)%>_form">
great job using a class here

2024-07-12 22:17 UTC, ahuynh3a commented on app/views/follow_requests/_form.html.erb
> +<%= form_with(model: follow_request, class: "d-inline-block" local: false) do |form| %>
great job being mindful of when to use local: false and when to use remote:true

2024-07-12 22:17 UTC, ahuynh3a commented on app/views/follow_requests/destroy.js.erb
> +var unfollow_btn = $(".<%=dom_id(@follow_request.recipient)%>_<%=dom_id(@follow_request.sender)%>_form")
I love that you used variables!

2024-07-12 22:17 UTC, ahuynh3a commented on app/views/follow_requests/destroy.js.erb
> +var unfollow_btn = $(".<%=dom_id(@follow_request.recipient)%>_<%=dom_id(@follow_request.sender)%>_form")
you are forgetting a semi-colon here so your follow/unfollow button is not working

2024-07-13 03:27 UTC, FadiBaker92 commented
Thank you for the feedback Annie! I  added the semicolon and removed the extra white spaces.

2024-07-14 04:36 UTC, ahuynh3a approved these changes
Thank you for making the changes!

2024-07-14 17:11 UTC, merged